name: Generate Assets

on:
  push:
    branches: [ main ]
    paths:
      - 'v2/icon.svg'
      - 'v2/icon-animate.svg'
      - '.github/workflows/generate-assets.yml'
      - 'scripts/generate_assets.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'v2/icon.svg'
      - 'v2/icon-animate.svg'
      - '.github/workflows/generate-assets.yml'
      - 'scripts/generate_assets.py'
  workflow_dispatch:

jobs:
  generate-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y librsvg2-bin imagemagick
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cairosvg pillow
        
    - name: Create output directories
      run: |
        mkdir -p assets/png
        mkdir -p assets/favicon
        mkdir -p assets/opengraph
        
    - name: Generate assets
      run: python scripts/generate_assets.py
      
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-generate assets from SVG icons"
        commit_user_name: "Sugeng Sulistiyawan"
        commit_user_email: "sugeng.sulistiyawan@gmail.com"
        commit_author: "Sugeng Sulistiyawan <sugeng.sulistiyawan@gmail.com>"
        file_pattern: "assets/"
        skip_dirty_check: false
